### ISSUE TITLE
Error en lectura de sesion

### ISSUE THREAD

**Issue by SebastianAyala07** [manucabral/pybrinf#3]
**Describe the bug**
Actualmente cuando se intenta leer el archivo de session del navegador, sucede un error debido a que el navegador est usando el archivo de session. Por lo tanto no se puede acceder a la session actual y por consiguiente tampoco al tab actual del usuario.

**To Reproduce**
Simplemente hice el uso de la libreria haciendo uso al mismo tiempo del navegador y de la ejecucion del script.

**Expected behavior**
Se esperaria que de alguna u otra forma pudiera leer esa session o que por medio de otra informacion del proceso del navegador se pueda realizar esta tarea (Obtener la url del tab activo)

**Screenshots**
![pybrinf error](https://user-images.githubusercontent.com/61714948/230507619-11844578-5fdc-494d-830e-ba9ac801e68b.PNG)
![pybrinf error1](https://user-images.githubusercontent.com/61714948/230507701-9c810001-aa8e-4783-b8cc-d905113cefbb.PNG)

**Desktop (please complete the following information):** 
Browser:
 - Name Microsoft Edge 
 - Version 112.0.1722.34
 - Name Chrome
 - Version 1.0.28.440
System:
- Name Windows
- Version 10

**Additional context**

**Comment by manucabral** [comment]
Hola Sebastian!

Lamentablemente no se puede copiar ni abrir el archivo de sesión mientras Google Chrome esta en ejecución si no hay privilegios, hablo de esto en la wiki [browser-session](https://github.com/manucabral/pybrinf/wiki/Quickstart#browser-session) pero podrías intentar cerrar la instancia de Google Chrome para después obtener la última sesión y después reabrir el navegador.

Por otro lado puedes utilizar la función dev tools para obtener en este caso las pestañas del navegador sin tener que cerrarlo, para acceder a esto necesitas abrir el navegador con dev tools activado (la única desventaja)

Te dejo dos scripts de ejemplo.
```py
# Este script abre el navegador por defecto con dev tools activado.
from pybrinf import Brinf
brinf = Brinf()
brinf.init()
browser = brinf.default_browser
browser.dev_tools = True
browser.open()
```

```py
# Este script obtiene las pestañas del navegador (recientemente abierto con dev tools activado)
from pybrinf import Brinf
brinf = Brinf()
brinf.init()
browser = brinf.default_browser
for tab in browser.tabs():
    # NOTA: El primer elemento es la pestaña activa siempre
    print(tab.url)
```

Salida
![image](https://user-images.githubusercontent.com/83357673/230809832-1c0ff61a-89ef-4194-b787-a22c8f2bce68.png)


Gracias por tu aporte.
