### ISSUE TITLE
PermissionError: [Errno 13] Permission denied 

### ISSUE THREAD

**Issue by yagoubigithub** [manucabral/pybrinf#4]
### python Version
3.11.4

### What operating system are you using?
windows 10

### browser
chrome Version 114.0.5735.199 (Build officiel) (64 bits)

### Expected Behavior
Should get  url on active tab of browser

### Actual Behavior
![image](https://github.com/manucabral/pybrinf/assets/17689500/f4cc73f8-af55-4154-aa10-50f6106f9aba)

I think the file already in use by chrome.exe that way this problem happen

Thanks

**Comment by manucabral** [comment]
Hi,
Due to security reasons, the session cannot be retrieved while the browser is running try running your python script as an administrator or use [dev tools](https://github.com/manucabral/pybrinf/wiki/Quickstart#dev-tools) option.
Thanks for your report.
